services:
    kgot:
        container_name: kgot_docker
        build:
            context: ../../
            dockerfile: ./docker_instances/kgot_docker/Dockerfile
        volumes:
            - ../../logs:/home/knowledge_graph_of_thoughts/logs
            - ../neo4j_docker/snapshots:/home/knowledge_graph_of_thoughts/docker_instances/neo4j_docker/snapshots
        command:
            [
                ". venv/bin/activate && ./run_multiple_gaia.sh --log_folder_base '${LOG_FOLDER_BASE}' --attachment_folder '${ATTACHMENT_FOLDER}' --config_llm_path '${CONFIG_LLM_PATH}' --logger_level ${LOGGER_LEVEL} --logger_file_mode '${LOGGER_FILE_MODE}' --neo4j_uri '${NEO4J_URI}' --neo4j_username '${NEO4J_USERNAME}' --neo4j_password '${NEO4J_PASSWORD}' --python_executor_uri '${PYTHON_EXECUTOR_URI}' --max_iterations ${MAX_ITERATIONS} --num_next_steps_decision ${NUM_NEXT_STEPS_DECISION} --max_retrieve_query_retry ${MAX_RETRIEVE_QUERY_RETRY} --max_cypher_fixing_retry ${MAX_CYPHER_FIXING_RETRY} --max_final_solution_parsing ${MAX_FINAL_SOLUTION_PARSING} --max_tool_retries ${MAX_TOOL_RETRIES} --max_llm_retries ${MAX_LLM_RETRIES} --llm_planning_model '${LLM_PLANNING_MODEL}' --llm_planning_temperature ${LLM_PLANNING_TEMPERATURE} --llm_execution_model '${LLM_EXECUTION_MODEL}' --llm_execution_temperature ${LLM_EXECUTION_TEMPERATURE} --controller_choice '${CONTROLLER_CHOICE}' --db_choice '${DB_CHOICE}' --tool_choice '${TOOL_CHOICE}' '${ZERO_SHOT}'",
            ]
        env_file:
            - .env
        networks:
            knowledge_graph:
                aliases:
                    - kgot_docker

networks:
    knowledge_graph:
        name: knowledge_graph
        driver: bridge
